<?php
require_once libraries_get_path('fpdf') . '/src/fpdf.php';
require_once libraries_get_path('tcpdf') . '/tcpdf.php';

/**
 * Implementation of hook_menu()
 */ 
function motionsplan_exercise_pdf_menu() {
    $items['node/%node/pdf'] = array(
        'title' => 'PDF',
        'page callback' => 'exercise_pdf_landscape',
        'page arguments' => array(1),
        'type' => MENU_LOCAL_TASK,
        'access callback' => 'exercise_pdf_access',
        'access arguments' => array(1)
    );
    $items['node/%node/pdf2'] = array(
        'title' => 'PDF2',
        'page callback' => 'exercise_pdf_portrait',
        'page arguments' => array(1),
        'type' => MENU_LOCAL_TASK,
        'access callback' => 'exercise_pdf_access',
        'access arguments' => array(1)
    ); 
    $items['node/%node/pdf3'] = array(
        'title' => 'PDF3',
        'page callback' => 'exercise_pdf_advanced',
        'page arguments' => array(1),
        'type' => MENU_LOCAL_TASK,
        'access callback' => 'exercise_pdf_access',
        'access arguments' => array(1)
    );
    $items['node/%node/print'] = array(
        'title' => 'PDF',
        'page callback' => 'article_pdf',
        'page arguments' => array(1),
        'type' => MENU_LOCAL_TASK,
        'access callback' => 'article_pdf_access',
        'access arguments' => array(1)
    );            
    $items['exerciseprogram/print_compact/%/pdf'] = array(
        'title' => t('PDF'),
        'page callback' => 'exerciseprogram_print_compact_pdf',
        'page arguments' => array(2),
        'access callback' => true,
        'type' => MENU_CALLBACK,
    );  
    $items['exerciseprogram/print_compact/%/exercisespdf'] = array(
        'title' => t('Exercise PDF cards'),
        'page callback' => 'exerciseprogram_print_compact_pdf_of_exercises',
        'page arguments' => array(2),
        'access callback' => true,
        'type' => MENU_CALLBACK,
    );        
    return $items;
}

function exercise_pdf_access($node) {
    if ($node->type != 'exercise') {
        return false;
    }
    return true;
}

function article_pdf_access($node) {
    if ($node->type != 'story') {
        return false;
    }
    return true;
}

class ExerciseProgramCompactPdf extends FPDF
{
    var $widths;
    var $aligns;
    var $imgs;

    /**
     * Set the array of column width
     */
    function SetWidths($w)
    {
        $this->widths=$w;
    }

    /**
     * Set the array of column alignments
     */
    function SetAligns($a)
    {
        $this->aligns=$a;
    }

    function Row($data, $pics = array())
    {
        //Calculate the height of the row
        $pic_width = 15;
        $pic_height = 15;
        $nb=0;
        for($i=0;$i<count($data);$i++) {
            $nb=max($nb,$this->NbLines($this->widths[$i],$data[$i]));
        }
        $h=5*$nb;


        if ($first_col = $this->NbLines($this->widths[$i], $data[0]) * 5 + $pic_height >= $h AND !empty($pics)) {
            $h = $first_col * 5 + $pic_height + 6;
        }

        //Issue a page break first if needed
        $this->CheckPageBreak($h);
        //Draw the cells of the row
        for($i=0;$i<count($data);$i++) {
            $w=$this->widths[$i];
            $a=isset($this->aligns[$i]) ? $this->aligns[$i] : 'L';
            //Save the current position
            $x=$this->GetX();
            $y=$this->GetY();
            //Draw the border
            $this->Rect($x,$y,$w,$h);
            //Print the text
            $this->MultiCell($w,5,$data[$i],0,$a);

            $calc_x = $x + 1;
            $calc_y = $this->GetY();
            if (!empty($pics)) {
                if ($i==0) {
                    foreach ($pics as $pic) {
                        if (file_exists($pic)) {
                            $this->Image($pic, $calc_x, $calc_y, $pic_width, $pic_height);
                            $calc_x += $pic_width;
                        }
                    }  
                }
            }
            //Put the position to the right of the cell
            $this->SetXY($x+$w,$y);
        }

        //Go to the next line
        $this->Ln($h);
    }

    /**
     * If the height h would cause an overflow, add a new page immediately
     */
    function CheckPageBreak($h)
    {
        if ($this->GetY()+$h>$this->PageBreakTrigger) {
            $this->AddPage($this->CurOrientation);
        }
    }
  
    /**
     * Computes the number of lines a MultiCell of width w will take
     */
    function NbLines($w,$txt)
    {
        $cw=&$this->CurrentFont['cw'];
        if ($w==0) {
            $w=$this->w-$this->rMargin-$this->x;
        }
        $wmax=($w-2*$this->cMargin)*1000/$this->FontSize;
        $s=str_replace("\r",'',$txt);
        $nb=strlen($s);
        if ($nb>0 and $s[$nb-1]=="\n") {
            $nb--;
        }
        $sep=-1;
        $i=0;
        $j=0;
        $l=0;
        $nl=1;
        while($i<$nb) {
            $c=$s[$i];
            if ($c=="\n") {
                $i++;
                $sep=-1;
                $j=$i;
                $l=0;
                $nl++;
                continue;
            }
            if ($c==' ') {
                $sep=$i;
            }
            $l+=$cw[$c];
            if ($l>$wmax) {
                if ($sep==-1) {
                    if ($i==$j) {
                        $i++;
                    }
                } else {
                    $i=$sep+1;
                }
                $sep=-1;
                $j=$i;
                $l=0;
                $nl++;
            } else {
                $i++;
            }
        }
        return $nl;
    }
}

class ExerciseAdvancedPdfPortrait extends TCPDF
{
    function __construct($disccache = false)
    {
        parent::__construct('P','mm','A4', true, 'UTF-8', $disccache);
        $this->SetAutoPageBreak(false);
        $this->SetMargins(0, 0, 0);  
        $this->AliasNbPages();        
    }

    function AddPage($node)
    {
        global $base_url;
        parent::AddPage();
        $this->SetMargins(0, 0, 0);  
        $this->setX(0);
        $this->setY(0);        
        $title = "  " . $node->title;
        $intro = $node->field_exercise_intro[0]['value'];
        $description = $node->field_exercise_guide[0]['value'];

        $keywords = array();
        foreach ($node->taxonomy as $taxonomy) {
            $keywords[] = $taxonomy->name;
        }

        $url = $base_url. '/node/' . $node->nid;
    
        $title_size = 20;

        $this->SetFont('Helvetica', 'B', $title_size);
        $this->SetTextColor(255, 255, 255);
        $this->Cell(0, 20, $title, null, 2, 'L', true);
    
        $this->SetLeftMargin(10);
        $this->SetRightMargin(10);
        
        $this->SetY(230);
        $this->SetX(10);
        $this->SetTextColor(0, 0, 0);

        $this->SetFont('Helvetica', null, 10);
        $this->MultiCell(40, 5, implode($keywords, "\n"), 0, 'C');

        if (!empty($node->field_exercise_images[0])) {
            $x = 10;
            $y = 25;
            $width = 0;
            $spacing = 3;
            $count = 0;
            $picture_rows = 1;
            $presetname = 'exercisePdfAdvanced';
            $preset = imagecache_preset_by_name($presetname);
            $pr_row = 0;
            foreach ($node->field_exercise_images as $image) {
                $src = $image["filepath"];
                $dst = imagecache_create_path($presetname, $src);
                if (file_exists($dst) || imagecache_build_derivative($preset['actions'], $src, $dst)) {
                    $file = $dst;
                    $size = getimagesize($file);
                    if ($size[0] < $size[1]) {
                        $orientation = 'portrait';
                        $pic_width = 25;
                        $new_line = 45;
                        $no_pr_row = 2;
                        if ($count > 8) {
                            break;
                        }
                    } else {
                        $orientation = 'landscape';
                        $pic_width = 55;
                        $new_line = 40;
                        $no_pr_row = 1;                        
                        if ($count > 5) {
                            break;
                        }
                    }
                    $width += $pic_width + $spacing;
        
                    if ($pr_row >= $no_pr_row) {
                        $y += $new_line;
                        $x = 10;
                        $picture_rows++;
                        $width = 0;
                        $pr_row = 0;
                    }
                    
                    $this->Image($file,$x,$y,$pic_width,0,'');
                    $x += $pic_width + $spacing;
                    $pr_row++;                    
                }
            }
        }
    
        $this->SetFont('Helvetica', 'B', 12);
        $this->setTextColor(0, 0, 0);
        $this->setY(30);
        $this->setX(70);
        $this->MultiCell(0, 7, $intro, 0, 'L');
        $this->Ln(4);
        $this->SetFont('Helvetica', null, 12);
        $this->setX(70);
        $this->MultiCell(0, 6, str_replace("\n",' ',$description), 0, 'L', false, 1, '', '', true, 0, true);

        $this->Image(dirname(__FILE__) . '/../../../themes/exercise/logo.png',8,270,50,0,'', 'http://motionsplan.dk/');
        $this->Image(dirname(__FILE__) . '/vih_logo.jpg',80,268,45,0,'', 'http://motionsplan.dk/');        
        $this->Image(dirname(__FILE__) . '/cc-by-sa_340x340.png',190,3,17,0,'');

        $this->SetFont('Helvetica', null, 8);
        $this->setY(280);
        $this->setX(6);
        $this->MultiCell(50, 8, $url, 0, 'C');

        $image_url = "http://chart.apis.google.com/chart?cht=qr&chs=100x100&chl=" . $url;
  
        $ch = curl_init();
        $timeout = 0;
        curl_setopt ($ch, CURLOPT_URL, $image_url);
        curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, $timeout);

        // Getting binary data
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_BINARYTRANSFER, 1);

        $image = curl_exec($ch);

        curl_close($ch);

        $f = fopen(dirname(__FILE__) . '/barcodes/'. md5(request_uri()) . '.png', 'w');
        fwrite($f, $image);
        fclose($f);

        $this->Image(dirname(__FILE__) . '/barcodes/' . md5(request_uri()) . '.png', 160, 245, 45, 0, '');
    }
}

class ExercisePdfPortrait extends FPDF
{
    function __construct()
    {
        parent::fpdf('P','mm','A4');
        $this->SetAutoPageBreak(false);
        $this->SetMargins(0, 0, 0);  
    }

    function AddPage($node)
    {
        global $base_url;
        parent::AddPage();
        $this->SetMargins(0, 0, 0);  
        $this->setX(0);
        $this->setY(0);        
        $title = "  " . utf8_decode($node->title);
        $description = utf8_decode(strip_tags($node->field_exercise_intro[0]['value']));
        $keywords = array();
        foreach ($node->taxonomy as $taxonomy) {
            $keywords[] = $taxonomy->name;
        }

        $url = $base_url. '/node/' . $node->nid;
    
        $title_size = 30;

        $this->SetFont('Helvetica', 'B', $title_size);

        $title_width = $this->GetStringWidth($title);
    
        if ($title_width > 200) {
            $title_size = 25;
        }
    
        $this->SetFont('Helvetica', 'B', $title_size);
        $this->SetTextColor(255, 255, 255);
        $this->Cell(0, 50, $title, null, 2, 'L', true);
    
        $this->SetLeftMargin(10);
        $this->SetRightMargin(10);
        $this->SetY(35);
        $this->SetFont('Helvetica', null, 10);
        $this->MultiCell(0, 5, utf8_decode(implode($keywords, ", ")), 0, 'L');

        $this->setY(60);

        if (!empty($node->field_exercise_images[0])) {
            $x = 10;
            $y = 60;
            $width = 0;
            $spacing = 5;
            $count = 0;
            $picture_rows = 1;
            $presetname = 'exercisePdf';
            $preset = imagecache_preset_by_name($presetname);
            foreach ($node->field_exercise_images as $image) {
                $src = $image["filepath"];
                $dst = imagecache_create_path($presetname, $src);
                $count++;                
                if (file_exists($dst) || imagecache_build_derivative($preset['actions'], $src, $dst)) {
                    $file = $dst;
                    $size = getimagesize($file);
                    if ($size[0] < $size[1]) {
                        $orientation = 'portrait';
                        $pic_width = 55;
                        $new_line = 80;
                        if ($count > 6) {
                            break;
                        }
                    } else {
                        $orientation = 'landscape';
                        $pic_width = 80;
                        $new_line = 68;
                        if ($count > 4) {
                            break;
                        }
                    }
                    $width += $pic_width + $spacing;
        
                    if ($width > 200) {
                        $y += $new_line;
                        $x = 10;
                        $picture_rows++;
                        $width = 0;
                    }
                    
                    $this->Image($file,$x,$y,$pic_width,0,'');
                    $x += $pic_width + $spacing;

                }
            }
            if ($orientation == 'portrait') {
                if ($picture_rows == 1) {
                    $this->setY(150);
                } else {
                    $this->setY(230);
                }
            } else {
                if ($picture_rows == 1) {
                    $this->setY(125);
                } else {
                    $this->setY(195);
                }
            }            
        }
    
        $this->SetFont('Helvetica', null, 17);
        $this->setTextColor(0, 0, 0);

        $this->MultiCell(0, 8, $description, 0);

        $this->Image(dirname(__FILE__) . '/../../../themes/motionsplan/logo.png',8,270,50,0,'', 'http://motionsplan.dk/');
        $this->Image(dirname(__FILE__) . '/vih_logo.jpg',80,268,45,0,'', 'http://motionsplan.dk/');        
        $this->Image(dirname(__FILE__) . '/cc-by-sa_340x340.png',190,3,17,0,'');

        $this->SetFont('Helvetica', null, 8);
        $this->setY(280);
        $this->setX(6);
        $this->MultiCell(50, 8, $url, 0, 'C');

        $image_url = "http://chart.apis.google.com/chart?cht=qr&chs=100x100&chl=" . $url;
  
        $ch = curl_init();
        $timeout = 0;
        curl_setopt ($ch, CURLOPT_URL, $image_url);
        curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, $timeout);

        // Getting binary data
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_BINARYTRANSFER, 1);

        $image = curl_exec($ch);

        curl_close($ch);

        $f = fopen(dirname(__FILE__) . '/barcodes/'. md5(request_uri()) . '.png', 'w');
        fwrite($f, $image);
        fclose($f);

        $this->Image(dirname(__FILE__) . '/barcodes/' . md5(request_uri()) . '.png', 160, 245, 45, 0, '');
    }
}

class ExercisePdfLandscape extends FPDF
{
    function __construct()
    {
        parent::fpdf('L','mm','A4');
        $this->SetAutoPageBreak(false);
    }

    function AddPage($node)
    {
        global $base_url;

        parent::AddPage();

        $title = utf8_decode($node->title);
        $description = utf8_decode(strip_tags($node->field_exercise_intro[0]['value']));
        $keywords = array();
        foreach ($node->taxonomy as $taxonomy) {
            $keywords[] = $taxonomy->name;
        }

        $url = $base_url. '/node/' . $node->nid;

        $this->SetFont('Helvetica', 'B', 26);
        $this->setTextColor(255, 255, 255);
        $this->Cell(0, 22, $title, null, 2, 'C', true);

        $this->SetFont('Helvetica', null, 17);
        $this->setTextColor(0, 0, 0);
        $this->setY(40);

        $this->MultiCell(200, 8, $description, 0);

        if (!empty($node->field_exercise_images[0])) {
            $x = 10;
            $y = 80;
            $width = 0;
            $spacing = 5;
            $count = 0;
            $presetname = 'exercisePdf';
            $preset = imagecache_preset_by_name($presetname);
            foreach ($node->field_exercise_images as $image) {
                $src = $image["filepath"];
                $dst = imagecache_create_path($presetname, $src);
                if (file_exists($dst) || imagecache_build_derivative($preset['actions'], $src, $dst)) {
                    $count++;
                    $file = $dst;
                    $size = getimagesize($file);
                    if ($size[0] < $size[1]) {
                        // portrait
                        $pic_width = 35;
                        $new_line = 60;
                        if ($count > 10) {
                            break;
                        }
                    } else {
                        // landscape
                        $pic_width = 55;
                        $new_line = 50;
                        if ($count > 6) {
                            break;
                        }
                    }
                    $width += $pic_width + $spacing;
    
                    if ($width > 200) {
                        $y += $new_line;
                        $x = 10;
                    }
    
                    $this->Image($file,$x,$y,$pic_width,0,'');
                    $x += $pic_width + $spacing;
                }            
            
            }
        }
    
        $this->Line(220, 30, 220, 220);
    
        $this->Image(dirname(__FILE__) . '/vih_logo.jpg',240,120,32,0,'', 'http://vih.dk/');
        $this->Image(dirname(__FILE__) . '/../../../themes/motionsplan/logo.png',235,180,50,0,'', 'http://motionsplan.dk/');

        $this->Image(dirname(__FILE__) . '/cc-by-sa_340x340.png',12,12,17,0,'');

        $this->setY(168);
        $this->SetFont('Helvetica', null, 10);

        $this->setY(40);
        $this->setX(233);

        $this->MultiCell(40, 5, utf8_decode(implode($keywords, "\n")), 0, 'C');

        $this->SetFont('Helvetica', null, 8);
        $this->setY(190);
        $this->setX(230);
        $this->MultiCell(60, 8, $url, 0, 'C');
    
        $image_url = "http://chart.apis.google.com/chart?cht=qr&chs=100x100&chl=" . $url;
    
        $ch = curl_init();
        $timeout = 0;
        curl_setopt ($ch, CURLOPT_URL, $image_url);
        curl_setopt ($ch, CURLOPT_CONNECTTIMEOUT, $timeout);
    
        // Getting binary data
        curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
        curl_setopt($ch, CURLOPT_BINARYTRANSFER, 1);
    
        $image = curl_exec($ch);
    
        curl_close($ch);
    
        $f = fopen(dirname(__FILE__) . '/barcodes/'. md5(request_uri()) . '.png', 'w');
        fwrite($f, $image);
        fclose($f);
    
        $this->Image(dirname(__FILE__) . '/barcodes/' . md5(request_uri()) . '.png', 235, 135, 45, 0, '');
    }
}

class ArticlePdf extends TCPDF
{
    protected $node;
    protected $url;

    function __construct($node)
    {
        global $base_url;            
        parent::__construct('P','mm','A4');
        $this->SetAutoPageBreak(true, 30);
        $this->SetMargins(10, 10, 10);  
        $this->AliasNbPages();        
        $this->node = $node;
        
        $this->url = $base_url. '/node/' . $this->node->nid;        
    }
    
    function Header()
    {
    }
    
    function Footer()
    {
        $this->Image(dirname(__FILE__) . '/../../../themes/motionsplan/logo.png',8,275,50,0,'', 'http://motionsplan.dk/');
        $this->Image(dirname(__FILE__) . '/vih_logo.jpg',155,270,45,0,'', 'http://vih.dk/');            
        $this->SetFont('Helvetica', null, 8);
        $this->setY(285);
        $this->setX(6);
        $this->MultiCell(50, 8, $this->url, 0, 'C');
        $this->SetY(-15);
        $this->SetFont('Helvetica', null, 12);        
        $this->Cell(0,10, $this->PageNo().'/{nb}',0,0,'C');
    }

    function AddContent()
    {
        parent::AddPage();
        $title = '  ' . $this->node->title;
        $body = check_markup($this->node->body, $this->node->format, false);

        $keywords = array();
        if (!empty($this->node->taxonomy)) {
            foreach ($this->node->taxonomy as $taxonomy) {
                $keywords[] = $taxonomy->name;
            }
        }

        if (!empty($this->node->field_article_image[0]['filepath'])) {
            $presetname = 'SlideshowPicture';
            $preset = imagecache_preset_by_name($presetname);
            $src = $this->node->field_article_image[0]['filepath'];
            $dst = imagecache_create_path($presetname, $src);
            if (file_exists($dst) || imagecache_build_derivative($preset['actions'], $src, $dst)) {
                $this->Image($dst,10,10,190,0,'', 'http://motionsplan.dk/');
            }        
        }
        $this->Image(dirname(__FILE__) . '/cc-by-sa_340x340.png', 180, 13, 17, 0, '');
    
        $this->SetY(43);
        $title_size = 15;
        $this->SetFont('Helvetica', 'B', $title_size);
        $this->SetTextColor(255, 255, 255);
        $this->Cell(0, 17, $title, null, 2, 'L', true);
    
        $this->Ln(8);
        $this->SetFont('Helvetica', 'N', 10);
        $this->SetTextColor(0, 0, 0);
        $this->writeHTML($body, true, false, true, false, '');        
    }
}

/**
 * Creates a pdf of an article node
 * 
 * @param $nid Node id
 *
 * @return void
 */
function article_pdf($node) {
    global $base_url;

    $title = $node->title;
    $pdf = new ArticlePdf($node);
    $pdf->SetTitle($title);
    $pdf->SetSubject('');
    $pdf->SetAuthor('Motionsplan.dk');
    $pdf->AddContent();
    $pdf->Output($title . '.pdf', 'I');
}


/**
 * Creates a pdf of an exercise node
 * 
 * @param $nid Node id
 *
 * @return void
 */
function exercise_pdf_portrait($node) {
    global $base_url;

    $title = utf8_decode($node->title);
    $pdf = new ExercisePdfPortrait();
    $pdf->SetTitle($title);
    $pdf->SetSubject('');
    $pdf->SetAuthor('Motionsplan.dk');
    $pdf->AddPage($node);
    $pdf->Output($title . '.pdf', 'I');
}

/**
 * Creates a pdf of an exercise node
 * 
 * @param $nid Node id
 *
 * @return void
 */
function exercise_pdf_landscape($node) {
    global $base_url;

    $title = utf8_decode($node->title);
    $pdf = new ExercisePdfLandscape();
    $pdf->SetTitle($title);
    $pdf->SetSubject('');
    $pdf->SetAuthor('Motionsplan.dk');
    $pdf->AddPage($node);
    $pdf->Output($title . '.pdf', 'I');
}

/**
 * Creates a pdf of an exercise node
 * 
 * @param $nid Node id
 *
 * @return void
 */
function exercise_pdf_advanced($node) {
    global $base_url;

    $title = utf8_decode($node->title);
    $pdf = new ExerciseAdvancedPdfPortrait();
    $pdf->SetTitle($title);
    $pdf->SetSubject('');
    $pdf->SetAuthor('Motionsplan.dk');
    $pdf->AddPage($node);
    $pdf->Output($title . '.pdf', 'I');
}

function exerciseprogram_print_compact_pdf_of_exercises() {
    global $base_path;
    $nids = exerciseprogram_get_nids(arg(2));
    if (sizeof($nids)<=0) {
        return '<strong>Du skal tilføje øvelser for at kunne udskrive</strong>';
    }

    $pdf = new ExercisePdfPortrait();
    $pdf->SetTitle(utf8_decode('Træningsøvelser'));
    $pdf->SetSubject('');
    $pdf->SetAuthor('Motionsplan.dk');

    foreach ($nids as $nid) {
        $node = node_load($nid);
        $pdf->AddPage($node);
    }
    $pdf->Output();
}

function exerciseprogram_print_compact_pdf() {
    global $base_path;
    $nids = exerciseprogram_get_nids(arg(2));
    if (sizeof($nids)<=0) {
        return '<strong>Du skal tilføje øvelser for at kunne udskrive</strong>';
    }
    
    $sql = "SELECT name, description FROM {exercise_program} WHERE pid = %d";
    $r = db_fetch_array(db_query($sql,arg(2)));

    $title = utf8_decode($r['name']);
    $description = utf8_decode($r['description']);

    $pdf = new ExerciseProgramCompactPdf();
    $pdf->SetTitle($title);
    $pdf->SetSubject('');
    $pdf->SetAuthor('Motionsplan.dk');
    $pdf->SetAutoPageBreak(false);

    $pdf->AddPage();
    $pdf->SetFont('Helvetica', 'B', 20);
    $pdf->Cell(0, 10, $title, null, 2, 'L', false);
    $pdf->Image(dirname(__FILE__) . '/../../../themes/motionsplan/logo.png',150,8,50,0,'', 'http://motionsplan.dk/');
    $pdf->setTextColor(0, 0, 0);

    $pdf->SetFont('Helvetica', null, 10);
    $pdf->MultiCell(180, 6, $description, 0);

    $pdf->SetY($pdf->GetY()+2);

    // table starts
    $pdf->SetWidths(array(50,70,70));
    $pdf->SetFont('Helvetica', 'B', 10);
    $pdf->Row(array(utf8_decode('Øvelse'), utf8_decode('Beskrivelse'), utf8_decode('Kommentar')));
    $pdf->SetFont('Helvetica', null, 10);

    $presetname = 'exercisePictureCompact';
    $preset = imagecache_preset_by_name($presetname);

    foreach($nids as $no => $eid) {
        $e = node_load($eid);

	    $imgs = array();
	    foreach($e->field_exercise_images as $img) {
            if (empty($img['filepath'])) { 
                continue; 
            }
            $src = $img["filepath"];
            $dst = imagecache_create_path($presetname, $src);
            if (file_exists($dst) || imagecache_build_derivative($preset['actions'], $src, $dst)) {
                $imgs[] = $dst;
            }
        }
	    if (sizeof($imgs) > 3) {
            $tmp_imgs = array();
            $tmp_imgs[] = $imgs[0];
            $tmp_imgs[] = $imgs[floor(sizeof($imgs)/2)];
            $tmp_imgs[] = $imgs[sizeof($imgs)-1];
            $imgs = $tmp_imgs;
        }

        $pdf->Row(array(utf8_decode($e->title), utf8_decode($e->field_exercise_intro[0]['value']), ''), $imgs); 
    }

    $pdf->Output($title . '.pdf', 'I');
}

function motionsplan_exercise_pdf_node_operations() {
    $operations = array(
        'pdf' => array(
            'label' => t('Print PDF (max 10)'), 
            'callback' => 'node_operations_pdf',
    ));
    return $operations;
}

function node_operations_pdf($nodes) {
    global $base_url;

    $title = 'Træningsøvelser';
    $pdf = new ExerciseAdvancedPdfPortrait(false);
    $pdf->SetTitle($title);
    $pdf->SetSubject('');
    $pdf->SetAuthor('Motionsplan.dk');
    $i = 0;
    $number = 10;
    foreach ($nodes as $node_id) {
        if ($i >= $number) {
            $error = true;
            break;
        }
        $node = node_load($node_id);
        if ($node->type != 'exercise') {
            continue;
        }
        $i++;
        $pdf->AddPage($node);
    }
    if ($error !== true) {
        $pdf->Output($title . '.pdf', 'D');
    } else {
        drupal_set_message(t('Can only print %number pages at a time', array('%number' => $number)), 'error');
    } 
    
    
}
