<?php

function motionsplanutils_form_alter(&$form, $form_state, $form_id) {
    if($form_id == 'story_node_form') {
        $form['submit_top'] = array (
                                '#type' => 'submit',
                                '#access' => true,
                                '#value' => 'Gem',
                                '#weight' => -10,
                                '#submit' =>
                                    array (
                                        0 => 'node_form_submit',
                                    ),
                                '#prefix' => '<br />',
                                );
    }
}
