<?php

function motionsplanutils_form_alter(&$form, $form_state, $form_id) {
    if($form_id == 'story_node_form') {
        $form['submit_top'] = array (
                                '#type' => 'submit',
                                '#access' => true,
                                '#value' => 'Gem',
                                '#weight' => -10,
                                '#submit' =>
                                    array (
                                        0 => 'node_form_submit',
                                    ),
                                '#prefix' => '<br />',
                                );
    }
}

function motionsplanutils_terms2keywords($t) {
    $keywords = array();
    if(!empty($t)) {
        foreach($t as $k) { $keywords[] = $k->name; }
    }
    return $keywords;
}

function motionsplanutils_meta() {
    $desc = '';
    $keywords = array();
 
    if(arg(0) == 'node') {
        $sql = "SELECT vid, type FROM {node} WHERE nid = %d";
        $res = db_fetch_array(db_query($sql,arg(1)));
        $vid = $res['vid'];
        $type = $res['type'];
        
        $fakeNode = (object)null;
        $fakeNode->nid = arg(1);
        $fakeNode->vid = $vid;
        
        if($type == 'exercise') {
            $sql = "SELECT field_exercise_intro_value FROM {content_type_exercise}
                    WHERE nid = %d";
            $desc = db_result(db_query($sql,arg(1)));    
        }
        elseif($type == 'story') {
            $sql = "SELECT teaser FROM {node_revisions} WHERE vid = %d";
            $desc = db_result(db_query($sql,$vid));
            $desc = strip_tags($desc);
            if(strlen($desc)>160) {
                $desc = substr($desc,0,155).'...';
            }
        }
        
        $terms = taxonomy_node_get_terms($fakeNode);
        $keywords = motionsplanutils_terms2keywords($terms);
        
    }
    elseif(arg(0) == 'frontpage') {
        $desc = 'Danmarks motions-, træning og fitness portal. Se alle vores illustrerede træningsøvelser - både med billeder og video.';
        $keywords = array('motion','træningsøvelser','øvelser','træningsprogrammer');
    }
    
    
    if(empty($keywords)) {
        $keywords = array('træningsøvelse','træningsprogram', 'træning', 'motion');
    }
    
    $meta = '';
    if(!empty($desc)) {
        $desc = str_replace(array("\n","\r"),'',$desc);
        $meta .= '<meta name="description" content="'.$desc.'" />'."\n";
    }
    if(!empty($keywords)) {
        $meta .= '<meta name="keywords" content="'.implode(', ',$keywords).'" />'."\n";
    }
	$meta .= '<meta name="copyright" content="Motionsplan.dk, 2009. All Rights Reserved" />';
	return $meta;
}
