<?php


function motionsplanblocks_block($op = 'list', $delta = 0, $edit = array()) {
    switch($op) {
        case 'list':
            $blocks['related_exercises']['info'] = t('Motionsplan - Related Exercises - Articles');
            return $blocks;
            break;
        
        case 'view':
            if($delta == 'related_exercises') {
                return motionsplanblocks_related_exercises();
            }
            break;
    }
}


function motionsplanblocks_related_exercises() {
    $title = 'Se øvelserne';
    
    $sql = "SELECT n.title, n.nid 
        FROM {content_field_related_exercises} c, node n
        WHERE n.nid = c.field_related_exercises_nid AND
            c.nid = %d ORDER BY c.delta";
    $res = db_query($sql,arg(1));
    
    $out = array();
    while($r = db_fetch_array($res)) {
        $out[] = l($r['title'],'node/'.$r['nid']);
    }
    if(sizeof($out)<=0) { return array(); }
    return array('subject'=>$title,'content'=>'<ul><li>'.implode('</li><li>',$out).'</li></ul>');
    
    
}
